# Generated by Django 3.1.5 on 2021-01-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearnModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kind', models.SmallIntegerField(choices=[(1, 'Куплю'), (2, 'Продам'), (3, 'Обменяю')], default=2)),
                ('Email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='Title')),
                ('MainText', models.TextField(null=True, verbose_name='Text')),
                ('Price', models.IntegerField(null=True, verbose_name='Price')),
                ('DataPublish', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-DataPublish', 'Title'],
            },
        ),
    ]
