# Generated by Django 3.1.5 on 2021-01-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnmodels',
            options={'verbose_name': 'LearnModel', 'verbose_name_plural': 'LearnModels'},
        ),
    ]
